In [8]:
records = [{'tz': 'America/New_York'}, {'tz': 'Europe/London'}]
time_zones = [rec.get('tz') for rec in records if isinstance(rec, dict) and 'tz' in rec]

time_zones[:10]

           



['America/New_York', 'Europe/London']

In [ ]:
import numpy as np
from numpy.random import randn
data = {i : randn() for i in range(7)}
data
data

{0: 0.2926534293749905,
 1: -0.019798864395955743,
 2: -0.8863263098567264,
 3: 0.6423309488384955,
 4: 1.3465391170046357,
 5: -0.1111220892134187,
 6: -0.5390190472029415}

In [15]:

def add_data(a, b):
    """Add two numbers."""
    return a + b

In [18]:
np.*load*?


np.__loader__
np.load
np.loadtxt

In [1]:
import numpy as np
from numpy.random import randn
data

NameError: name 'data' is not defined

In [ ]:
data = [6, 7.5, 8, 0, 1]
arr1 = np.array(data)
print(arr1)
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr1.dtype)
print(arr2.dtype)

print(np.zeros(10))
print(np.zeros((3,6)))
print(np.empty((2,3,2)))

np.arange(15)





[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
float64
int64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[7.27733070e-312 2.81617418e-322]
  [0.00000000e+000 0.00000000e+000]
  [4.24512503e+175 2.42336543e-057]]

 [[7.42763974e-091 1.79616205e-052]
  [8.26682643e-072 1.53459004e-075]
  [6.48224659e+170 4.93432906e+257]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
import numpy as np
from numpy.random import randn
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Function Description
array: Convert input data (list, tuple, array, or other sequence type) to an ndarray either by
inferring a dtype or explicitly specifying a dtype. Copies the input data by default.

asarray: Convert input to ndarray, but do not copy if the input is already an ndarray

arange: Like the built-in range but returns an ndarray instead of a list.

ones, ones_like: Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype.

zeros, zeros_like: Like ones and ones_like but producing arrays of 0’s instead

empty, empty_like: Create new arrays by allocating new memory, but do not populate with any values like ones and zeros

eye, identity: Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)

In [23]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')